[window]
decorations = "None"

[font]
size = 14

[colors]
bright.black = '#535353'
bright.blue = '#9fa9ff'
bright.cyan = '#8df9ff'
bright.green = '#22ff18'
bright.magenta = '#e09aff'
bright.red = '#fb0007'
bright.white = '#ffffff'
bright.yellow = '#fedc2b'

cursor.cursor = '#d0d0d0'
cursor.text = '#151515'

normal.black = '#000000'
normal.blue = '#5665ff'
normal.cyan = '#50d2da'
normal.green = '#1cd915'
normal.magenta = '#b052da'
normal.red =  '#d70005'
normal.white =  '#e0e0e0'
normal.yellow = '#d9bd26'

primary.background = '#090909'
primary.foreground = '#cdcdcd'

selection.background = '#780002'
selection.text = '#ececec'
