export PATH=${HOME}/.cargo/bin:$PATH
export PATH=${HOME}/.npm-global/bin/:$PATH
export PATH=${HOME}/.config/yarn/global/:$PATH
export PATH=${HOME}/go/bin:$PATH
export PATH=/opt/homebrew/bin:$PATH

export GOPATH=${HOME}/go
export ZSH=$HOME/.oh-my-zsh

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

ZSH_THEME="powerlevel10k/powerlevel10k"

ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"

plugins=(git)

source $ZSH/oh-my-zsh.sh

bindkey -v

unalias gcb

gcb() { git checkout -b "@sergeichestakov/$@"; }
cdl() { cd "$@" && ls; }

fdb() {
  local branches branch
  branches=$(git for-each-ref --count=30 --sort=-committerdate refs/heads/ --format="%(refname:short)") &&
  branch=$(echo "$branches" | fzf --multi) &&
  git branch -D $(echo "$branch" | sed "s/.* //" | sed "s#remotes/[^/]*/##")
}

export LANG=en_US.UTF-8
export EDITOR='nvim'
export VISUAL='nvim'
export INITVIM=$HOME/.config/nvim/init.vim
export ZSHRC=$HOME/.zshrc
export TMUXCONF=$HOME/.tmux.conf
export NVM_DIR=$HOME/.nvm
export MCFLY_FUZZY=5
export MCFLY_RESULTS=50
export FZF_DEFAULT_COMMAND='rg --color auto --files'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

alias cat='bat'
alias ls='eza'
alias python='python3'
alias vim='nvim'
alias gs="git status"
alias gd="git diff"
alias gdb='git branch -D'
alias pr="gh pr view --web"
alias pn="pnpm"
alias reattach='tmux attach-session -t'
alias ggpush='git push -u origin "$(git_current_branch)"'
[ $(uname) = "Darwin" ] && alias tmux='env TERM=screen-256color-italic tmux'

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

source "$(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh"

bindkey '`' autosuggest-accept

[ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && source "$NVM_DIR/bash_completion"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/.zshrc.local ] && source ~/.zshrc.local

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/bit bit

eval "$(mcfly init zsh)"

# pnpm
export PNPM_HOME="/Users/sergeichestakov/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
