export PATH=${HOME}/.cargo/bin:$PATH
export PATH=${HOME}/.npm-global/bin/:$PATH
export PATH=${HOME}/.config/yarn/global/:$PATH
export PATH=${HOME}/go/bin:$PATH
export PATH=/usr/local/go/bin:$PATH

export GOPATH=${HOME}/go
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"

ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"

plugins=(git)

source $ZSH/oh-my-zsh.sh

unalias gcb

gcb() { git checkout -b "@sergeichestakov/$@"; }
cdl() { cd "$@" && ls; }

export LANG=en_US.UTF-8
export EDITOR='nvim'
export VISUAL='nvim'
export INITVIM=$HOME/.config/nvim/init.vim
export ZSHRC=$HOME/.zshrc
export TMUXCONF=$HOME/.tmux.conf
export FZF_DEFAULT_COMMAND='rg --color auto --files'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

alias cat='bat'
alias python='python3'
alias vim='nvim'
alias reattach='tmux attach-session -t'
# alias tmux='env TERM=screen-256color-italic tmux'

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
