export PATH=${HOME}/.cargo/bin:$PATH
export PATH=${HOME}/.npm-global/bin/:$PATH
export PATH=${HOME}/.config/yarn/global/:$PATH
export PATH=${HOME}/Library/Android/sdk/tools/bin:$PATH
export PATH=${HOME}/go/bin:$PATH
export PATH=/opt/homebrew/bin:$PATH
export PATH=/usr/local/go/bin:$PATH
export PATH=/Users/sergeichestakov/Library/Python/3.9/bin:$PATH
export PATH=/Applications/Xcode.app/Contents/Developer/usr/bin/:$PATH

export GOPATH=${HOME}/go
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"

ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"

plugins=(git)

source $ZSH/oh-my-zsh.sh

bindkey -v

if [ $(uname) = "Darwin" ]; then
  fpath+=("$(brew --prefix)/share/zsh/site-functions")
  autoload -U promptinit; promptinit
  prompt pure
fi

unalias gcb

gcb() { git checkout -b "@sergeichestakov/$@"; }
cdl() { cd "$@" && ls; }

fdb() {
  local branches branch
  branches=$(git for-each-ref --count=30 --sort=-committerdate refs/heads/ --format="%(refname:short)") &&
  branch=$(echo "$branches" | fzf --multi) &&
  git branch -D $(echo "$branch" | sed "s/.* //" | sed "s#remotes/[^/]*/##")
}

export LANG=en_US.UTF-8
export EDITOR='nvim'
export VISUAL='nvim'
export INITVIM=$HOME/.config/nvim/init.vim
export ZSHRC=$HOME/.zshrc
export TMUXCONF=$HOME/.tmux.conf
export NVM_DIR=$HOME/.nvm
export MCFLY_FUZZY=5
export MCFLY_RESULTS=50
export FZF_DEFAULT_COMMAND='rg --color auto --files'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

alias cat='bat'
alias ls='eza'
alias python='python3'
alias vim='nvim'
alias gs="git status"
alias gd="git diff"
alias gdb='git branch -D'
alias pr="gh pr view --web"
alias pn="pnpm"
alias reattach='tmux attach-session -t'
alias ggpush='git push -u origin "$(git_current_branch)"'
[ $(uname) = "Darwin" ] && alias tmux='env TERM=screen-256color-italic tmux'

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh

bindkey '`' autosuggest-accept

[ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && source "$NVM_DIR/bash_completion"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/.zshrc.local ] && source ~/.zshrc.local

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/bit bit

eval "$(mcfly init zsh)"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/sergeichestakov/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/sergeichestakov/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/sergeichestakov/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/sergeichestakov/Downloads/google-cloud-sdk/completion.zsh.inc'; fi

# pnpm
export PNPM_HOME="/Users/sergeichestakov/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

